import type {
    SalesInvoice,
    PurchaseInvoice,
    VatPeriodSummary,
    ReportingPeriod,
  } from "../types/invoice";
  
  const REPORTING_PERIODS: ReportingPeriod[] = [
    { label: "Q1 2025 (Jan – Mar)", value: "Q1-2025", startDate: "2025-01-01", endDate: "2025-03-31" },
    { label: "Q4 2024 (Oct – Dec)", value: "Q4-2024", startDate: "2024-10-01", endDate: "2024-12-31" },
    { label: "Q3 2024 (Jul – Sep)", value: "Q3-2024", startDate: "2024-07-01", endDate: "2024-09-30" },
    { label: "Q2 2024 (Apr – Jun)", value: "Q2-2024", startDate: "2024-04-01", endDate: "2024-06-30" },
    { label: "Jan 2025", value: "Jan-2025", startDate: "2025-01-01", endDate: "2025-01-31" },
    { label: "Feb 2025", value: "Feb-2025", startDate: "2025-02-01", endDate: "2025-02-28" },
    { label: "Mar 2025", value: "Mar-2025", startDate: "2025-03-01", endDate: "2025-03-31" },
    { label: "Dec 2024", value: "Dec-2024", startDate: "2024-12-01", endDate: "2024-12-31" },
  ];
  
  const SALES_INVOICES_BY_PERIOD: Record<string, SalesInvoice[]> = {
    "Q1-2025": [
      {
        id: "si-001",
        irn: "NRS-2025-INV-00291847",
        qrCodeRef: "QR-NRS-291847",
        invoiceNumber: "INV-2025-001",
        customerName: "Dangote Industries Ltd",
        customerTIN: "TIN-1234567890",
        invoiceDate: "2025-01-15",
        dueDate: "2025-02-15",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "li-001-a",
            description: "Business Consulting Services",
            quantity: 1,
            unitPrice: 2500000,
            netAmount: 2500000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 187500,
            total: 2687500,
          },
          {
            id: "li-001-b",
            description: "Tax Advisory",
            quantity: 1,
            unitPrice: 1500000,
            netAmount: 1500000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 112500,
            total: 1612500,
          },
        ],
        netAmount: 4000000,
        vatAmount: 300000,
        total: 4300000,
      },
      {
        id: "si-002",
        irn: "NRS-2025-INV-00291902",
        qrCodeRef: "QR-NRS-291902",
        invoiceNumber: "INV-2025-002",
        customerName: "MTN Nigeria Plc",
        customerTIN: "TIN-9876543210",
        invoiceDate: "2025-01-22",
        dueDate: "2025-02-22",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "li-002-a",
            description: "Cybersecurity Assessment",
            quantity: 1,
            unitPrice: 5000000,
            netAmount: 5000000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 375000,
            total: 5375000,
          },
        ],
        netAmount: 5000000,
        vatAmount: 375000,
        total: 5375000,
      },
      {
        id: "si-003",
        irn: "NRS-2025-INV-00292041",
        qrCodeRef: "QR-NRS-292041",
        invoiceNumber: "INV-2025-003",
        customerName: "United Nations Nigeria",
        customerTIN: "TIN-UN-DIPLOMATIC",
        invoiceDate: "2025-02-05",
        dueDate: "2025-03-05",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "li-003-a",
            description: "Humanitarian Project Support",
            quantity: 1,
            unitPrice: 3200000,
            netAmount: 3200000,
            vatCategory: "zero-rated",
            vatRate: 0,
            vatAmount: 0,
            total: 3200000,
          },
        ],
        netAmount: 3200000,
        vatAmount: 0,
        total: 3200000,
      },
      {
        id: "si-004",
        irn: "NRS-2025-INV-00292188",
        qrCodeRef: "QR-NRS-292188",
        invoiceNumber: "INV-2025-004",
        customerName: "Lagos State Government",
        customerTIN: "TIN-LSG-001",
        invoiceDate: "2025-02-18",
        dueDate: "2025-03-18",
        fiscalizationStatus: "validated",
        paymentStatus: "unpaid",
        lineItems: [
          {
            id: "li-004-a",
            description: "Data Analytics Platform",
            quantity: 1,
            unitPrice: 8000000,
            netAmount: 8000000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 600000,
            total: 8600000,
          },
          {
            id: "li-004-b",
            description: "Training Program",
            quantity: 3,
            unitPrice: 500000,
            netAmount: 1500000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 112500,
            total: 1612500,
          },
        ],
        netAmount: 9500000,
        vatAmount: 712500,
        total: 10212500,
      },
      {
        id: "si-005",
        irn: "",
        qrCodeRef: "",
        invoiceNumber: "INV-2025-005",
        customerName: "Zenith Bank Plc",
        customerTIN: "TIN-ZNB-002",
        invoiceDate: "2025-03-01",
        dueDate: "2025-04-01",
        fiscalizationStatus: "rejected",
        paymentStatus: "unpaid",
        lineItems: [
          {
            id: "li-005-a",
            description: "Compliance Audit",
            quantity: 1,
            unitPrice: 6000000,
            netAmount: 6000000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 450000,
            total: 6450000,
          },
        ],
        netAmount: 6000000,
        vatAmount: 450000,
        total: 6450000,
      },
      {
        id: "si-006",
        irn: "NRS-2025-INV-00292567",
        qrCodeRef: "QR-NRS-292567",
        invoiceNumber: "INV-2025-006",
        customerName: "Access Bank Plc",
        customerTIN: "TIN-ACB-003",
        invoiceDate: "2025-03-10",
        dueDate: "2025-04-10",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "li-006-a",
            description: "M&A Advisory",
            quantity: 1,
            unitPrice: 12000000,
            netAmount: 12000000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 900000,
            total: 12900000,
          },
        ],
        netAmount: 12000000,
        vatAmount: 900000,
        total: 12900000,
      },
      {
        id: "si-007",
        irn: "NRS-2025-INV-00292710",
        qrCodeRef: "QR-NRS-292710",
        invoiceNumber: "INV-2025-007",
        customerName: "NNPC Ltd",
        customerTIN: "TIN-NNPC-004",
        invoiceDate: "2025-03-20",
        dueDate: "2025-04-20",
        fiscalizationStatus: "validated",
        paymentStatus: "unpaid",
        lineItems: [
          {
            id: "li-007-a",
            description: "Sustainability Consulting",
            quantity: 1,
            unitPrice: 4500000,
            netAmount: 4500000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 337500,
            total: 4837500,
          },
          {
            id: "li-007-b",
            description: "Export Processing Zone Equipment",
            quantity: 2,
            unitPrice: 1200000,
            netAmount: 2400000,
            vatCategory: "zero-rated",
            vatRate: 0,
            vatAmount: 0,
            total: 2400000,
          },
        ],
        netAmount: 6900000,
        vatAmount: 337500,
        total: 7237500,
      },
    ],
    "Q4-2024": [
      {
        id: "si-q4-001",
        irn: "NRS-2024-INV-00198823",
        qrCodeRef: "QR-NRS-198823",
        invoiceNumber: "INV-2024-087",
        customerName: "Flutterwave Inc",
        customerTIN: "TIN-FLW-007",
        invoiceDate: "2024-10-12",
        dueDate: "2024-11-12",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "li-q4-001-a",
            description: "Digital Transformation Strategy",
            quantity: 1,
            unitPrice: 9000000,
            netAmount: 9000000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 675000,
            total: 9675000,
          },
        ],
        netAmount: 9000000,
        vatAmount: 675000,
        total: 9675000,
      },
      {
        id: "si-q4-002",
        irn: "NRS-2024-INV-00199445",
        qrCodeRef: "QR-NRS-199445",
        invoiceNumber: "INV-2024-088",
        customerName: "Nigerian Breweries Plc",
        customerTIN: "TIN-NB-008",
        invoiceDate: "2024-11-05",
        dueDate: "2024-12-05",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "li-q4-002-a",
            description: "HR Consulting Services",
            quantity: 1,
            unitPrice: 3500000,
            netAmount: 3500000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 262500,
            total: 3762500,
          },
        ],
        netAmount: 3500000,
        vatAmount: 262500,
        total: 3762500,
      },
    ],
  };
  
  const PURCHASE_INVOICES_BY_PERIOD: Record<string, PurchaseInvoice[]> = {
    "Q1-2025": [
      {
        id: "pi-001",
        irn: "NRS-2025-INV-00187392",
        qrCodeRef: "QR-NRS-187392",
        invoiceNumber: "SUPP-2025-1092",
        supplierName: "Microsoft Nigeria Ltd",
        supplierTIN: "TIN-MSFT-001",
        invoiceDate: "2025-01-08",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-001-a",
            description: "Office 365 Enterprise Licenses (50 seats)",
            quantity: 50,
            unitPrice: 45000,
            netAmount: 2250000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 168750,
            total: 2418750,
            claimableStatus: "CLAIMABLE",
            claimableVatAmount: 168750,
          },
          {
            id: "pli-001-b",
            description: "Azure Cloud Services",
            quantity: 1,
            unitPrice: 980000,
            netAmount: 980000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 73500,
            total: 1053500,
            claimableStatus: "CLAIMABLE",
            claimableVatAmount: 73500,
          },
        ],
        netAmount: 3230000,
        vatAmount: 242250,
        total: 3472250,
        overallClaimableStatus: "CLAIMABLE",
      },
      {
        id: "pi-002",
        irn: "NRS-2025-INV-00187891",
        qrCodeRef: "QR-NRS-187891",
        invoiceNumber: "SUPP-2025-2201",
        supplierName: "Lagos Office Supplies Co",
        supplierTIN: "TIN-LOS-002",
        invoiceDate: "2025-01-20",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-002-a",
            description: "Office Stationery and Supplies",
            quantity: 1,
            unitPrice: 350000,
            netAmount: 350000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 26250,
            total: 376250,
            claimableStatus: "PARTIALLY_CLAIMABLE",
            claimablePercent: 60,
            claimableVatAmount: 15750,
            reasonCode: "PARTIAL_BUSINESS_USE",
          },
        ],
        netAmount: 350000,
        vatAmount: 26250,
        total: 376250,
        overallClaimableStatus: "PARTIALLY_CLAIMABLE",
      },
      {
        id: "pi-003",
        irn: "",
        qrCodeRef: "",
        invoiceNumber: "SUPP-2025-0831",
        supplierName: "Abuja Catering Services",
        supplierTIN: "TIN-ACS-003",
        invoiceDate: "2025-02-10",
        fiscalizationStatus: "pending",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-003-a",
            description: "Catering Services (Staff Events)",
            quantity: 1,
            unitPrice: 800000,
            netAmount: 800000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 60000,
            total: 860000,
            claimableStatus: "REVIEW_REQUIRED",
            claimableVatAmount: 0,
            reasonCode: "MISSING_FISCALIZED_INVOICE",
          },
        ],
        netAmount: 800000,
        vatAmount: 60000,
        total: 860000,
        overallClaimableStatus: "REVIEW_REQUIRED",
      },
      {
        id: "pi-004",
        irn: "NRS-2025-INV-00188445",
        qrCodeRef: "QR-NRS-188445",
        invoiceNumber: "SUPP-2025-3312",
        supplierName: "GTBank Financial Services",
        supplierTIN: "TIN-GTB-004",
        invoiceDate: "2025-02-14",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-004-a",
            description: "Interest on Business Loan",
            quantity: 1,
            unitPrice: 1200000,
            netAmount: 1200000,
            vatCategory: "exempt",
            vatRate: 0,
            vatAmount: 0,
            total: 1200000,
            claimableStatus: "NOT_CLAIMABLE",
            claimableVatAmount: 0,
            reasonCode: "EXEMPT_ACTIVITY",
          },
          {
            id: "pli-004-b",
            description: "POS Terminal Fees (VAT applicable)",
            quantity: 1,
            unitPrice: 45000,
            netAmount: 45000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 3375,
            total: 48375,
            claimableStatus: "CLAIMABLE",
            claimableVatAmount: 3375,
          },
        ],
        netAmount: 1245000,
        vatAmount: 3375,
        total: 1248375,
        overallClaimableStatus: "PARTIALLY_CLAIMABLE",
      },
      {
        id: "pi-005",
        irn: "NRS-2025-INV-00189102",
        qrCodeRef: "QR-NRS-189102",
        invoiceNumber: "SUPP-2025-4401",
        supplierName: "Andela Technologies",
        supplierTIN: "TIN-AND-005",
        invoiceDate: "2025-02-28",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-005-a",
            description: "Software Development Services",
            quantity: 1,
            unitPrice: 4500000,
            netAmount: 4500000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 337500,
            total: 4837500,
            claimableStatus: "CLAIMABLE",
            claimableVatAmount: 337500,
          },
        ],
        netAmount: 4500000,
        vatAmount: 337500,
        total: 4837500,
        overallClaimableStatus: "CLAIMABLE",
      },
      {
        id: "pi-006",
        irn: "NRS-2025-INV-00189771",
        qrCodeRef: "QR-NRS-189771",
        invoiceNumber: "SUPP-2025-5509",
        supplierName: "Cornerstone Insurance Plc",
        supplierTIN: "TIN-CIS-006",
        invoiceDate: "2025-03-05",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-006-a",
            description: "Business Insurance Premium",
            quantity: 1,
            unitPrice: 2100000,
            netAmount: 2100000,
            vatCategory: "exempt",
            vatRate: 0,
            vatAmount: 0,
            total: 2100000,
            claimableStatus: "NOT_CLAIMABLE",
            claimableVatAmount: 0,
            reasonCode: "EXEMPT_ACTIVITY",
          },
        ],
        netAmount: 2100000,
        vatAmount: 0,
        total: 2100000,
        overallClaimableStatus: "NOT_CLAIMABLE",
      },
      {
        id: "pi-007",
        irn: "NRS-2025-INV-00190023",
        qrCodeRef: "QR-NRS-190023",
        invoiceNumber: "SUPP-2025-6611",
        supplierName: "Oando Energy Resources",
        supplierTIN: "TIN-OND-007",
        invoiceDate: "2025-03-12",
        fiscalizationStatus: "rejected",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-007-a",
            description: "Diesel Fuel Supply",
            quantity: 5000,
            unitPrice: 1200,
            netAmount: 6000000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 450000,
            total: 6450000,
            claimableStatus: "NOT_CLAIMABLE",
            claimableVatAmount: 0,
            reasonCode: "INVOICE_REJECTED_BY_NRS",
          },
        ],
        netAmount: 6000000,
        vatAmount: 450000,
        total: 6450000,
        overallClaimableStatus: "NOT_CLAIMABLE",
      },
      {
        id: "pi-008",
        irn: "NRS-2025-INV-00190445",
        qrCodeRef: "QR-NRS-190445",
        invoiceNumber: "SUPP-2025-7720",
        supplierName: "Deloitte Nigeria",
        supplierTIN: "TIN-DLT-008",
        invoiceDate: "2025-03-25",
        fiscalizationStatus: "validated",
        paymentStatus: "unpaid",
        lineItems: [
          {
            id: "pli-008-a",
            description: "Actuarial Services",
            quantity: 1,
            unitPrice: 3800000,
            netAmount: 3800000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 285000,
            total: 4085000,
            claimableStatus: "CLAIMABLE",
            claimableVatAmount: 285000,
          },
        ],
        netAmount: 3800000,
        vatAmount: 285000,
        total: 4085000,
        overallClaimableStatus: "CLAIMABLE",
      },
    ],
    "Q4-2024": [
      {
        id: "pi-q4-001",
        irn: "NRS-2024-INV-00155001",
        qrCodeRef: "QR-NRS-155001",
        invoiceNumber: "SUPP-2024-9901",
        supplierName: "KPMG Advisory Services",
        supplierTIN: "TIN-KPMG-001",
        invoiceDate: "2024-10-18",
        fiscalizationStatus: "validated",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-q4-001-a",
            description: "Tax Compliance Review",
            quantity: 1,
            unitPrice: 5500000,
            netAmount: 5500000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 412500,
            total: 5912500,
            claimableStatus: "CLAIMABLE",
            claimableVatAmount: 412500,
          },
        ],
        netAmount: 5500000,
        vatAmount: 412500,
        total: 5912500,
        overallClaimableStatus: "CLAIMABLE",
      },
      {
        id: "pi-q4-002",
        irn: "NRS-2024-INV-00156234",
        qrCodeRef: "QR-NRS-156234",
        invoiceNumber: "SUPP-2024-0012",
        supplierName: "Unregistered Vendor XYZ",
        supplierTIN: "",
        invoiceDate: "2024-11-22",
        fiscalizationStatus: "pending",
        paymentStatus: "paid",
        lineItems: [
          {
            id: "pli-q4-002-a",
            description: "Office Renovation",
            quantity: 1,
            unitPrice: 2000000,
            netAmount: 2000000,
            vatCategory: "standard",
            vatRate: 7.5,
            vatAmount: 150000,
            total: 2150000,
            claimableStatus: "NOT_CLAIMABLE",
            claimableVatAmount: 0,
            reasonCode: "SUPPLIER_NOT_REGISTERED",
          },
        ],
        netAmount: 2000000,
        vatAmount: 150000,
        total: 2150000,
        overallClaimableStatus: "NOT_CLAIMABLE",
      },
    ],
  };
  
  function computeSummary(
    salesInvoices: SalesInvoice[],
    purchaseInvoices: PurchaseInvoice[],
    period: string
  ): VatPeriodSummary {
    const fiscalizedSales = salesInvoices.filter((i) => i.fiscalizationStatus === "validated");
    const outputVat = fiscalizedSales.reduce((sum, i) => sum + i.vatAmount, 0);
  
    let claimable = 0;
    let partial = 0;
    let notClaimable = 0;
    let reviewRequired = 0;
  
    purchaseInvoices.forEach((inv) => {
      if (inv.fiscalizationStatus !== "validated") return;
      inv.lineItems.forEach((li) => {
        if (li.claimableStatus === "CLAIMABLE") claimable += li.claimableVatAmount;
        else if (li.claimableStatus === "PARTIALLY_CLAIMABLE") partial += li.claimableVatAmount;
        else if (li.claimableStatus === "NOT_CLAIMABLE") notClaimable += li.vatAmount;
        else if (li.claimableStatus === "REVIEW_REQUIRED") reviewRequired += li.vatAmount;
      });
    });
  
    const totalInputVat = purchaseInvoices.reduce((sum, i) => sum + i.vatAmount, 0);
    const claimableTotal = claimable + partial;
  
    return {
      period,
      outputVat,
      claimableInputVat: claimable,
      partiallyClaimableInputVat: partial,
      notClaimableInputVat: notClaimable,
      reviewRequiredInputVat: reviewRequired,
      totalInputVat,
      vatPayable: outputVat - claimableTotal,
      salesInvoiceCount: salesInvoices.length,
      purchaseInvoiceCount: purchaseInvoices.length,
      fiscalizedSalesCount: fiscalizedSales.length,
      fiscalizedPurchaseCount: purchaseInvoices.filter((i) => i.fiscalizationStatus === "validated").length,
      excludedFromCalculation: salesInvoices.filter((i) => i.fiscalizationStatus !== "validated").length,
    };
  }
  
  export async function fetchReportingPeriods(): Promise<ReportingPeriod[]> {
    return new Promise((resolve) => setTimeout(() => resolve(REPORTING_PERIODS), 200));
  }
  
  export async function fetchVatSummary(period: string): Promise<VatPeriodSummary> {
    const sales = SALES_INVOICES_BY_PERIOD[period] ?? [];
    const purchases = PURCHASE_INVOICES_BY_PERIOD[period] ?? [];
    return new Promise((resolve) =>
      setTimeout(() => resolve(computeSummary(sales, purchases, period)), 400)
    );
  }
  
  export async function fetchSalesInvoices(period: string): Promise<SalesInvoice[]> {
    const data = SALES_INVOICES_BY_PERIOD[period] ?? [];
    return new Promise((resolve) => setTimeout(() => resolve(data), 300));
  }
  
  export async function fetchPurchaseInvoices(period: string): Promise<PurchaseInvoice[]> {
    const data = PURCHASE_INVOICES_BY_PERIOD[period] ?? [];
    return new Promise((resolve) => setTimeout(() => resolve(data), 300));
  }
  